apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-server
  labels:
    app: upload-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-server
  template:
    metadata:
      labels:
        app: upload-server
    spec:
      containers:
      - name: upload-server
        image: quay.io/wangzheng422/qimgs:uplaod.server-v1.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: upload-server
spec:
  selector:
    app: upload-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: upload-server
spec:
  to:
    kind: Service
    name: upload-server
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow