- name: Deploy upload-server to OpenShift
  hosts: localhost
  vars:
    namespace: "{{ target_namespace }}"
  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"


    - name: Apply deployment configuration
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../gitops/upload.server/deployment.yaml') }}"
        namespace: "{{ namespace }}"

