- name: Remove upload-server from OpenShift
  hosts: localhost
  vars:
    namespace: target_namespace  # Parameterized namespace
  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"

    - name: List files and sizes in /app/uploads
      kubernetes.core.k8s_exec:
        namespace: "{{ namespace }}"
        pod: "{{ item.metadata.name }}"
        command: "ls -lh /app/uploads"
      with_items: "{{ lookup('kubernetes.core.k8s', kind='Pod', namespace=namespace, label_selector='app=upload-server').resources }}"
      register: upload_files

    - debug:
        msg: "{{ item.stdout }}"
      with_items: "{{ upload_files.results }}"

    - name: Delete deployment configuration
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('file', '../gitops/upload.server/deployment.yaml') }}"
        namespace: "{{ namespace }}"
