---
- name: Run command in pod-description-writer pods
  hosts: localhost
  vars:
    namespace: your_namespace  # Parameterized namespace
    pod_name: your_pod_name    # Parameterized pod name
  tasks:
    - name: Get the specified pod
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
        name: "{{ pod_name }}"
      register: pod

    - name: Execute command in the specified pod
      kubernetes.core.k8s_exec:
        namespace: "{{ namespace }}"
        pod: "{{ pod.resources[0].metadata.name }}"
        command: ls /
      register: command_result

    - name: Display command output
      debug:
        msg: "{{ command_result.stdout }}"