---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-description-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-description-writer
  template:
    metadata:
      labels:
        app: pod-description-writer
    spec:
      containers:
      - name: my-app-heap-dump
        image: quay.io/wangzheng422/qimgs:simple-java-http-server-threads-2024.07.05.v04
        volumeMounts:
        - mountPath: /wzh-log
          name: wzh-log-volume
      volumes:
      - name: wzh-log-volume
        emptyDir: {}